---
- name: Create Container of app
  hosts: all
  tasks:
    - name: web container
      docker_container:
        name: testcalci
        image: ajayupadhyay007/scientificcalc-master
        state: started
        ports:
          - "8083:8083"
        tty: true
        detach: true